# @domain:   product
# @module:   formatter
# @loc:      gh_main
# @status:   stable
# @depends:  NONE

"""Dossier formatter — renders ResearchArtifact for human consumption.

Mirrors cls_leads.formatter / workspace.case._generate_report_md: a plain
Markdown document with clearly separated sections matching the dossier's
own field separation (topic definition / collected items / findings /
gaps / provenance), so the rendering adds no interpretation beyond
formatting.
"""

from __future__ import annotations

import json

from cls_research.schemas import ResearchArtifact


def dossier_to_markdown(artifact: ResearchArtifact) -> str:
    td = artifact.topic_definition
    lines = [
        f"# Research Dossier: {artifact.topic_name}",
        "",
        f"**Topic ID:** `{artifact.topic_id}`  ",
        f"**Dossier ID:** `{artifact.dossier_id}`  ",
        f"**Version:** {artifact.version}  ",
        f"**Status:** {artifact.status}  ",
        f"**Generated:** {artifact.generated_at}  ",
        f"**Run ID:** `{artifact.run_id}`",
        "",
        "## Topic Definition",
        "",
        f"**Core question:** {td.get('core_question', '')}",
        "",
    ]

    if td.get("subquestions"):
        lines.append("**Subquestions:**")
        for sq in td["subquestions"]:
            lines.append(f"- {sq}")
        lines.append("")

    lines.extend([
        f"**Keywords:** {', '.join(td.get('keywords', [])) or '_none_'}",
        "",
        f"**Entities:** {', '.join(td.get('entities', [])) or '_none_'}",
        "",
        f"**Geographies:** {', '.join(td.get('geographies', [])) or '_none_'}",
        "",
        f"**Time horizon:** {td.get('time_horizon_days', '')} days",
        "",
        f"**Source classes:** {', '.join(td.get('source_classes', [])) or '_none declared_'}",
        "",
        f"**Exclusions:** {', '.join(td.get('exclusions', [])) or '_none_'}",
        "",
    ])

    if td.get("analyst_notes"):
        lines.extend(["**Analyst notes:**", "", td["analyst_notes"], ""])

    lines.extend([
        "## Notable Findings",
        "",
    ])
    if artifact.notable_findings:
        for f in artifact.notable_findings:
            lines.append(f"- {f}")
    else:
        lines.append("_None recorded this version._")
    lines.append("")

    lines.extend([
        "## Unresolved Questions / Collection Gaps",
        "",
    ])
    if artifact.unresolved_questions:
        for g in artifact.unresolved_questions:
            lines.append(f"- {g}")
    else:
        lines.append("_No open gaps recorded this version._")
    lines.append("")

    lines.extend([
        f"## Collected Items ({len(artifact.collected_items)} total)",
        "",
    ])
    if artifact.collected_items:
        lines.append("| Published | Source | Matched Terms | Credibility | Title / URL |")
        lines.append("|---|---|---|---|---|")
        for item in sorted(artifact.collected_items, key=lambda i: i.get("published_at") or "", reverse=True):
            cred = item.get("credibility_annotation")
            cred_str = f"{cred:.2f}" if isinstance(cred, (int, float)) else "—"
            title = (item.get("title") or "").replace("|", "/")
            url = item.get("url", "")
            terms = ", ".join(item.get("matched_terms", []))
            lines.append(
                f"| {item.get('published_at', '')} | {item.get('source', '')} | {terms} | "
                f"{cred_str} | [{title}]({url}) |"
            )
        lines.append("")
    else:
        lines.append("_No items collected._")
        lines.append("")

    lines.extend([
        "## Provenance",
        "",
        "```json",
        json.dumps(artifact.provenance, indent=2, default=str),
        "```",
        "",
        "---",
        "*Generated by SPEC-1 Research Mode (cls_research) — deterministic collection, "
        "no opaque scoring. Findings and gaps above are rule-based; see "
        "docs/research_mode.md for the exact rules applied.*",
    ])

    return "\n".join(lines)


def dossier_to_json(artifact: ResearchArtifact) -> dict:
    """Return the dossier as a plain dict suitable for JSON serialisation."""
    return artifact.to_dict()
