#!/usr/bin/env python3
# @domain:   spec-1
# @module:   harvest_index
# @loc:      gh_main
# @status:   stable
# @depends:  NONE

import os
import re
import sys
import argparse
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT    = Path(__file__).parent.parent
OUTPUT       = REPO_ROOT / "INDEX.md"
EXTENSIONS   = {".py", ".sh", ".sql", ".yaml", ".toml", ".md", ".cfg", ".ini"}
SKIP_DIRS    = {"_ARCHIVE", ".git", "__pycache__", "node_modules", ".venv", "venv", "dist", "build"}
TAG_PATTERN  = re.compile(r"#\s*@(\w+):\s*(.+)")
STATUS_ORDER = ["stable", "testing", "drafting", "deprecated"]

def extract_tags(filepath):
    tags = {}
    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            for i, line in enumerate(f):
                if i > 25:
                    break
                m = TAG_PATTERN.match(line.strip())
                if m:
                    tags[m.group(1)] = m.group(2).strip()
    except Exception:
        pass
    return tags

def harvest(filter_domain=None, filter_status=None, filter_loc=None):
    entries = []
    for root, dirs, files in os.walk(REPO_ROOT):
        dirs[:] = sorted([d for d in dirs if d not in SKIP_DIRS])
        for fname in sorted(files):
            fpath = Path(root) / fname
            if fpath.suffix not in EXTENSIONS:
                continue
            rel  = fpath.relative_to(REPO_ROOT)
            tags = extract_tags(fpath)
            if not tags:
                continue
            if filter_domain and tags.get("domain", "") != filter_domain:
                continue
            if filter_status and tags.get("status", "") != filter_status:
                continue
            if filter_loc and tags.get("loc", "") != filter_loc:
                continue
            entries.append((rel, tags))
    return entries

def write_index(entries):
    by_domain = {}
    for rel, tags in entries:
        domain = tags.get("domain", "untagged")
        by_domain.setdefault(domain, []).append((rel, tags))

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# SPEC-1 INDEX\n\n",
        "_Auto-generated by scripts/harvest_index.py. Do not edit manually._\n\n",
        f"**Generated:** {now}  \n",
        f"**Indexed:** {len(entries)} tagged files across {len(by_domain)} domains\n\n",
        "---\n\n",
        "## Concept Matrix\n\n",
        "| domain | total | stable | testing | drafting | _SCRATCH |\n",
        "|--------|-------|--------|---------|----------|----------|\n",
    ]

    for domain in sorted(by_domain):
        items   = by_domain[domain]
        total   = len(items)
        stable  = sum(1 for _, t in items if t.get("status") == "stable")
        testing = sum(1 for _, t in items if t.get("status") == "testing")
        draft   = sum(1 for _, t in items if t.get("status") == "drafting")
        scratch = sum(1 for _, t in items if t.get("loc") == "_SCRATCH")
        lines.append(f"| {domain} | {total} | {stable} | {testing} | {draft} | {scratch} |\n")

    lines.append("\n---\n\n")

    for domain in sorted(by_domain):
        lines.append(f"## {domain}\n\n")
        lines.append("| module | loc | status | depends | path |\n")
        lines.append("|--------|-----|--------|---------|------|\n")

        def sort_key(item):
            _, t = item
            s = t.get("status", "unknown")
            return (STATUS_ORDER.index(s) if s in STATUS_ORDER else 99, t.get("module", ""))

        for rel, tags in sorted(by_domain[domain], key=sort_key):
            module  = tags.get("module",  "—")
            loc     = tags.get("loc",     "—")
            status  = tags.get("status",  "—")
            depends = tags.get("depends", "—")
            lines.append(f"| {module} | `{loc}` | {status} | {depends} | `{rel}` |\n")
        lines.append("\n")

    scratch_items = [(r, t) for r, t in entries if t.get("loc") in ("_SCRATCH", "claude_cloud")]
    if scratch_items:
        lines.append("---\n\n## Open Work Queue\n\n")
        lines.append("_Files pending promotion to gh_main._\n\n")
        lines.append("| module | domain | status | path |\n")
        lines.append("|--------|--------|--------|------|\n")
        for rel, tags in scratch_items:
            lines.append(
                f"| {tags.get('module','—')} | {tags.get('domain','—')} "
                f"| {tags.get('status','—')} | `{rel}` |\n"
            )
        lines.append("\n")

    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"[OK] INDEX.md written — {len(entries)} files / {len(by_domain)} domains")
    if scratch_items:
        print(f"[!!] {len(scratch_items)} file(s) pending promotion to gh_main")

def print_matrix(entries):
    by_domain = {}
    for rel, tags in entries:
        domain = tags.get("domain", "untagged")
        by_domain.setdefault(domain, []).append((rel, tags))

    print(f"\n{'DOMAIN':<20} {'MODULE':<30} {'LOC':<15} {'STATUS'}")
    print("-" * 80)
    for domain in sorted(by_domain):
        for rel, tags in by_domain[domain]:
            print(
                f"{tags.get('domain','—'):<20} "
                f"{tags.get('module','—'):<30} "
                f"{tags.get('loc','—'):<15} "
                f"{tags.get('status','—')}"
            )
    print()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SPEC-1 Index Harvester")
    parser.add_argument("--domain", help="Filter by @domain tag")
    parser.add_argument("--status", help="Filter by @status tag")
    parser.add_argument("--loc",    help="Filter by @loc tag")
    parser.add_argument("--print",  action="store_true", help="Print to stdout only")
    args = parser.parse_args()

    results = harvest(
        filter_domain=args.domain,
        filter_status=args.status,
        filter_loc=args.loc,
    )

    if not results:
        print("[WARN] No tagged files found matching filters.")
        sys.exit(0)

    if args.print:
        print_matrix(results)
    else:
        write_index(results)
